game_manager
{
	spawn
	{	
	    wm_mapdescription "Allied forces are attempting to steal supply documents from an Axis warehouse complex."
	
		// Game rules
		wm_axis_respawntime	30
		wm_allied_respawntime 25		
		wm_set_round_timelimit 10		
		
		// Axis control all objectives at the start (0 == AXIS, 1 == ALLIED)
		wm_set_objective_status	1 0
		wm_set_objective_status	2 0
		wm_set_objective_status	3 0
		wm_set_objective_status	4 0
		wm_set_objective_status	5 0
		wm_set_objective_status	6 -1

		wm_objective_allied_desc 1 "Primary Objective:**Steal the Axis supply documents."
		wm_objective_allied_desc 2 "Primary Objective:**Get to the Transmitter and radio the Supply Documents."
		wm_objective_allied_desc 3 "Secondary Objective:**Breach the Service Door."
		wm_objective_allied_desc 4 "Secondary Objective:**Breach the Axis Storage Wall."
		wm_objective_allied_desc 5 "Secondary Objective:**Destroy the Main Door."
		wm_objective_allied_desc 6 "Secondary Objective:**Secure the Upper Complex."

		wm_objective_axis_desc 1 "Primary Objective:**Prevent Allies from stealing the supply documents."
		wm_objective_axis_desc 2 "Primary Objective:**Stop the Allies before they transmit the supply documents."
		wm_objective_axis_desc 3 "Primary Objective:**Prevent the Allies from destroying the Service Door."
		wm_objective_axis_desc 4 "Primary Objective:**Prevent the Allies from destroying the Storage Wall."
		wm_objective_axis_desc 5 "Primary Objective:**Do not let the Allies breach the complex."
		wm_objective_axis_desc 6 "Secondary Objective:**Hold the Upper Complex."

		wm_objective_image 1 "objectives/ae_frostbite_1.jpg"
		wm_objective_image 2 "objectives/ae_frostbite_2.jpg"
		wm_objective_image 3 "objectives/ae_frostbite_3.jpg"
		wm_objective_image 4 "objectives/ae_frostbite_4.jpg"
	    wm_objective_image 5 "objectives/ae_frostbite_5.jpg"
		wm_objective_image 6 "objectives/ae_frostbite_6.jpg"
		
        wm_overview_image "overview/ae_frostbite.jpg"
		
		wm_objective_short_axis_desc 1 "Defend the Supply Documents"
		wm_objective_short_axis_desc 2 "Stop the Allies from Transmitting"
		wm_objective_short_axis_desc 3 "Defend the Service Door"
		wm_objective_short_axis_desc 4 "Defend the Storage Wall"
		wm_objective_short_axis_desc 5 "Defend the Main Door"
		wm_objective_short_axis_desc 6 "Hold the Upper Complex"

		wm_objective_short_allied_desc 1 "Steal the Supply Documents"
		wm_objective_short_allied_desc 2 "Transmit the Supply Documents"
		wm_objective_short_allied_desc 3 "Destroy the Service Door"
		wm_objective_short_allied_desc 4 "Destroy the Storage Wall"
		wm_objective_short_allied_desc 5 "Destroy the Main Door"
		wm_objective_short_allied_desc 6 "Capture the Upper Complex"
		
		// Set the number of objectives for the map
		wm_number_of_objectives	6

		// Set Defending Team for SW Mode
		wm_set_defending_team 0

		// Set the round winner:  0 == AXIS, 1 == ALLIED
		wm_setwinner 0
				
		// wait for everything to settle
		wait 1500 
	}
		
	trigger axis_object_stolen
	{
		// Change the objective state internally, so UI can update, etc.
		// Allied have stolen the documents (0 == AXIS, 1 == ALLIED)
		wm_set_objective_status	1 1
	}

	trigger axis_object_returned
	{
		// Change the objective state internally, so UI can update, etc.
		// Axis have returned the documents (0 == AXIS, 1 == ALLIED)
		wm_set_objective_status	1 0
	}
	
	trigger allies_transmit
	{
	    wm_announce "The Allies have transmitted the Supply Documents!" 
		wm_setwinner 1
		wm_endround
	}
		
	trigger sound_alarm
	{
		wait 1000
		alertentity sound_alarm
	}
}

service_door
{
	spawn
	{
	}
	
	death
	{
		wm_announce	"The Service Door has been breached!"
		trigger game_manager sound_alarm
		
		wm_set_objective_status	3 1
	}
}

storage_wall_explosive
{
	spawn
	{
	}
		
	death
	{
		wm_announce "The Storage Wall has been breached!" 
		trigger game_manager sound_alarm
		
		wm_set_objective_status 4 1
	}
}

main_door
{
	spawn
	{
	}
	
	death
	{
		wm_announce "The Main Door has been breached!" 
		trigger game_manager sound_alarm
		
		wm_set_objective_status 5 1
	}
}

forward_respawn
{
	spawn
	{
	}

	trigger axis_capture
	{		
		wm_announce	"Axis reclaims the Upper Complex!"
		wm_set_objective_status	6 -1
	}

	trigger allied_capture
	{		
		wm_announce	"Allies capture the Upper Complex!"
		wm_set_objective_status	6 1
	}
}

transmitter
{
	death
	{
		trigger game_manager allies_transmit
	}
}

gramophone
{
	trigger play
	{
		//playanim <startframe> <endframe> [looping forever/duration] [rate FPS]
		playanim 0 78 looping 42900 //3.9 seconds for a loop (78frames 20fps)
	}
}

gramophone_trigger
{
	trigger play
	{
		trigger gramophone play
	}
}