name: Build
on: [create]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create ae_editor.pk3
        run: 7z a -tzip "ae_editor_${{ github.event.release.tag_name }}.pk3" "@ae_editor.txt"
      - name: Create ae_pak0.pk3
        run: 7z a -tzip "ae_pak0_${{ github.event.release.tag_name }}.pk3" "@ae_pak0.txt"
      - name: Create ae_adlernest.pk3
        run: 7z a -tzip "ae_adlernest_${{ github.event.release.tag_name }}.pk3" "@ae_adlernest.txt"
      - name: Create ae_frostbite.pk3
        run: 7z a -tzip "ae_frostbite_${{ github.event.release.tag_name }}.pk3" "@ae_frostbite.txt"
      - name: 'Upload ae_main'
        uses: actions/upload-artifact@v2
        with:
          name: "ae_main_${{ github.event.release.tag_name }}"
          path: |
            "ae_editor_${{ github.event.release.tag_name }}.pk3"
            "ae_pak0_${{ github.event.release.tag_name }}.pk3"
            "ae_adlernest_${{ github.event.release.tag_name }}.pk3"
            "ae_frostbite_${{ github.event.release.tag_name }}.pk3"